"""add code chunks

Revision ID: 13fa0ebf6980
Revises: c3a8097e646e
Create Date: 2026-09-16 23:45:07.698012

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13fa0ebf6980"
down_revision: str | Sequence[str] | None = "c3a8097e646e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_chunks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=2048), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("symbol_name", sa.String(length=512), nullable=False),
        sa.Column("symbol_type", sa.String(length=50), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("parent", sa.String(length=512), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id",
            "commit_sha",
            "file_path",
            "start_line",
            "end_line",
            name="uq_code_chunks_repository_commit_location",
        ),
    )
    op.create_index("ix_code_chunks_content_hash", "code_chunks", ["content_hash"], unique=False)
    op.create_index("ix_code_chunks_repository_id", "code_chunks", ["repository_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_code_chunks_repository_id", table_name="code_chunks")
    op.drop_index("ix_code_chunks_content_hash", table_name="code_chunks")
    op.drop_table("code_chunks")
    # ### end Alembic commands ###
