"""create pull requests

Revision ID: c3a8097e646e
Revises: 609178ada5e0
Create Date: 2026-09-16 20:44:50.355791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3a8097e646e"
down_revision: str | Sequence[str] | None = "609178ada5e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("github_pr_id", sa.Integer(), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_branch", sa.String(length=255), nullable=False),
        sa.Column("target_branch", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("approval_status", sa.String(length=32), nullable=False),
        sa.Column("github_url", sa.String(length=2048), nullable=True),
        sa.Column("review_summary", sa.Text(), nullable=True),
        sa.Column("merge_commit_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_pr_id"),
    )
    op.create_index(
        op.f("ix_pull_requests_approval_status"), "pull_requests", ["approval_status"], unique=False
    )
    op.create_index(op.f("ix_pull_requests_status"), "pull_requests", ["status"], unique=False)
    op.create_index(op.f("ix_pull_requests_task_id"), "pull_requests", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pull_requests_task_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_status"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_approval_status"), table_name="pull_requests")
    op.drop_table("pull_requests")
    # ### end Alembic commands ###
