"""create file changes

Revision ID: cce5acb7c102
Revises: df34857dd045
Create Date: 2026-09-16 20:38:32.798594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cce5acb7c102"
down_revision: str | Sequence[str] | None = "df34857dd045"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=2048), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("before_content", sa.Text(), nullable=True),
        sa.Column("after_content", sa.Text(), nullable=True),
        sa.Column("diff", sa.Text(), nullable=True),
        sa.Column("before_hash", sa.String(length=128), nullable=True),
        sa.Column("after_hash", sa.String(length=128), nullable=True),
        sa.Column("line_additions", sa.Integer(), nullable=False),
        sa.Column("line_deletions", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_changes_agent_run_id"), "file_changes", ["agent_run_id"], unique=False
    )
    op.create_index(op.f("ix_file_changes_file_path"), "file_changes", ["file_path"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_changes_file_path"), table_name="file_changes")
    op.drop_index(op.f("ix_file_changes_agent_run_id"), table_name="file_changes")
    op.drop_table("file_changes")
    # ### end Alembic commands ###
